# Generated by OpenQL 0.11.1 for program example
version 1.2

pragma @ql.name("example")


.newKernel
    rz q[0], 4.585729798199446
    skip 1
    ry q[0], -2.0547749040346277
    skip 1
    { # start at cycle 4
        rz q[0], 0.641722846152555
        rz q[1], -0.7181926665243731
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[1], 1.5897331666902788
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], -3.994196313860317
    skip 1
    ry q[0], -0.9188793478850865
    skip 1
    { # start at cycle 20
        rz q[0], 2.068710471488518
        ry q[1], 1.9831196844348746
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    ry q[1], 0.8156108035199139
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], 0.4711671912321788
    skip 1
    ry q[0], -2.49907414131406
    skip 1
    { # start at cycle 36
        rz q[0], -0.9770377475519063
        rz q[1], -1.0254217734843156
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[1], 0.9578667088194192
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], 2.596218100279213
    skip 1
    ry q[0], -0.8246157544043087
    skip 1
    { # start at cycle 52
        rz q[0], -0.9398720558218223
        rz q[2], -0.8456954918275841
    }
    skip 1
    cnot q[0], q[2]
    skip 3
    rz q[2], -0.607056985554568
    skip 1
    cnot q[1], q[2]
    skip 3
    rz q[2], -0.2706829699717043
    skip 1
    cnot q[0], q[2]
    skip 3
    rz q[2], 1.541478063523275
    skip 1
    { # start at cycle 72
        cnot q[1], q[2]
        rz q[0], -4.162719411613713
    }
    skip 1
    ry q[0], -1.6212397711762878
    skip 1
    { # start at cycle 76
        rz q[0], -0.7522336340014002
        rz q[1], 1.3252573061256694
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[1], -0.723892352293291
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], -2.8960536329205664
    skip 1
    ry q[0], -0.7282601276021141
    skip 1
    { # start at cycle 92
        rz q[0], 1.279498451862826
        ry q[1], 1.370835437255926
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    ry q[1], 0.8214321849706199
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], 0.0408047761334455
    skip 1
    ry q[0], -1.5153106829694625
    skip 1
    { # start at cycle 108
        rz q[0], 0.02296442499828224
        rz q[1], 1.3681301377499984
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[1], 1.7544997397790145
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], 3.3442588426346913
    skip 1
    ry q[0], -0.8465761448197227
    skip 1
    { # start at cycle 124
        rz q[0], 0.9859899293252599
        ry q[2], 1.6284990066055782
    }
    skip 1
    cnot q[0], q[2]
    skip 3
    ry q[2], 0.28897907965137926
    skip 1
    cnot q[1], q[2]
    skip 3
    ry q[2], 0.026069554038919418
    skip 1
    cnot q[0], q[2]
    skip 3
    ry q[2], 0.47194934968331953
    skip 1
    { # start at cycle 144
        cnot q[1], q[2]
        rz q[0], 1.5760147537736653
    }
    skip 1
    ry q[0], -2.206949842245437
    skip 1
    { # start at cycle 148
        rz q[0], -1.9223280609493776
        rz q[1], -1.9004546645607008
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[1], -1.19873815921883
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], -2.8119343158239887
    skip 1
    ry q[0], -0.21989053767916694
    skip 1
    { # start at cycle 164
        rz q[0], -0.42621190337434056
        ry q[1], 1.0442875553315094
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    ry q[1], 0.49565525590855003
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], -1.4147810211996807
    skip 1
    ry q[0], -1.7458083922772758
    skip 1
    { # start at cycle 180
        rz q[0], -0.487794255987526
        rz q[1], -1.6538166533092753
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[1], 1.4682714541648998
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], 0.08302032651437918
    skip 1
    ry q[0], -0.8924979246132408
    skip 1
    { # start at cycle 196
        rz q[0], 1.5177630000431626
        rz q[2], -0.8132003625704673
    }
    skip 1
    cnot q[0], q[2]
    skip 3
    rz q[2], 1.4200612166698101
    skip 1
    cnot q[1], q[2]
    skip 3
    rz q[2], 0.8792858527829646
    skip 1
    cnot q[0], q[2]
    skip 3
    rz q[2], 0.15443937365551252
    skip 1
    { # start at cycle 216
        cnot q[1], q[2]
        rz q[0], 0.024778508558000567
    }
    skip 1
    ry q[0], -0.3151630038461521
    skip 1
    { # start at cycle 220
        rz q[0], -1.3723462155192065
        rz q[1], 0.6434712852173364
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[1], 1.3094331007200717
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], -2.2142676120122333
    skip 1
    ry q[0], -0.252297194505938
    skip 1
    { # start at cycle 236
        rz q[0], -1.7491395271468506
        ry q[1], 1.4511368959532478
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    ry q[1], 0.5310626990106931
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], 0.9427424476099133
    skip 1
    ry q[0], -1.4526663391692574
    skip 1
    { # start at cycle 252
        rz q[0], 1.970070855005129
        rz q[1], -1.9010485374455108
    }
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[1], -1.1370442338586038
    skip 1
    cnot q[0], q[1]
    skip 3
    rz q[0], 3.471844864240408
    skip 1
    ry q[0], -1.421680892970042
    skip 1
    rz q[0], 0.2513526160232864
    skip 1
