./qule --matrix_type QFT --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.000001
./qule --matrix_type QFT --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.00001
./qule --matrix_type QFT --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.0001
./qule --matrix_type QFT --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.001
./qule --matrix_type QFT --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.01
./qule --matrix_type Had --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.000001
./qule --matrix_type Had --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.00001
./qule --matrix_type Had --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.0001
./qule --matrix_type Had --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.001
./qule --matrix_type Had --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.01
./qule --matrix_type grover --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.000001
./qule --matrix_type grover --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.00001
./qule --matrix_type grover --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.0001
./qule --matrix_type grover --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.001
./qule --matrix_type grover --method GDP* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.01
./qule --matrix_type QFT --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.000001
./qule --matrix_type QFT --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.00001
./qule --matrix_type QFT --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.0001
./qule --matrix_type QFT --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.001
./qule --matrix_type QFT --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.01
./qule --matrix_type Had --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.000001
./qule --matrix_type Had --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.00001
./qule --matrix_type Had --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.0001
./qule --matrix_type Had --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.001
./qule --matrix_type Had --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.01
./qule --matrix_type grover --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.000001
./qule --matrix_type grover --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.00001
./qule --matrix_type grover --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.0001
./qule --matrix_type grover --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.001
./qule --matrix_type grover --method DLR* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.01
./qule --matrix_type QFT --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.000001
./qule --matrix_type QFT --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.00001
./qule --matrix_type QFT --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.0001
./qule --matrix_type QFT --method GDLM* --n 8 --num_tests 5 --alpha 0.01 --add_noise --noise_mag 0.001
# ./qule --matrix_type QFT --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.01
./qule --matrix_type Had --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.000001
./qule --matrix_type Had --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.00001
./qule --matrix_type Had --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.0001
./qule --matrix_type Had --method GDLM* --n 8 --num_tests 5 --alpha 0.01 --add_noise --noise_mag 0.001
# ./qule --matrix_type Had --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.01
./qule --matrix_type grover --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.000001
./qule --matrix_type grover --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.00001
./qule --matrix_type grover --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.0001
./qule --matrix_type grover --method GDLM* --n 8 --num_tests 5 --alpha 0.01 --add_noise --noise_mag 0.001
./qule --matrix_type grover --method GDLM* --n 8 --num_tests 5 --alpha 0.1 --add_noise --noise_mag 0.01